### ISSUE TITLE
Planners can drive into joint limits

### ISSUE THREAD

**Issue by jeking04** [personalrobotics/prpy#104]
I have seen a few instances where the result of executing a plan seems to leave the arm outside of joint limits.  This is a problem because owd will fail silently on any future trajectories sent to the arm.

**Comment by mkoval** [comment]
Do you have any idea why this is happening? The OpenRAVE robot has padded joint limits, so this should not be an issue.

**Comment by mkoval** [comment]
I believe we isolated this to the OpenRAVE BiRRT. This has not been an issue since we removed that planner from the default sequence in HerbPy.
