### ISSUE TITLE
Add basic unit tests for planners

### ISSUE THREAD

**Issue by mkoval** [personalrobotics/prpy#106]
We've been burned several times recently by planners failing for silly reasons (e.g. typos in member variable names). There is now quite a large set of planners in PrPy---we use eight in HERB's default planning pipeline alone---and several different `@PlanningMethods`. It's virtually impossible to manually test all of these combinations before making a commit.

I started writing some very basic unit tests ([in this branch](https://github.com/personalrobotics/prpy/tree/feature/PlanningUnitTests)) to help with this. My initial goal is to just make **some call** to each `@PlanningMethod`. My goal here is to catch typos, not compute benchmarks. In most cases, these are very easy queries in the `wamtest` environment shipped with OpenRAVE.

I'd like to get this minimal level of coverage on the planners in HERB's default planning pipeline. This issue is mostly just a list to track our progress:

- [x] `SnapPlanner`
    - [x] `PlanToConfiguration`
    - [x] `PlanToEndEffectorPose`
- [ ] `VectorFieldPlanner`
    - [ ] `PlanToEndEffectorPose`
    - [x] `PlanToEndEffectorOffset`
    - [ ] `FollowVectorField`
- [ ] `GreedyIkPlanner`
    - [ ] `PlanToEndEffectorPose`
    - [x] `PlanToEndEffectorOffset`
    - [ ] `PlanWorkspacePath`
- [ ] `CHOMPPlanner`
    - [ ] `PlanToConfiguration`
    - [ ] `PlanToEndEffectorPose`
    - [ ] `OptimizeTrajectory`
- [ ] `BiRRTPlanner`
    - [x] `PlanToConfiguration`
    - [ ] `PlanToConfigurations`
- [ ] `CBiRRTPlanner`
    - [x] `PlanToConfiguration`
    - [ ] `PlanToConfigurations`
    - [x] `PlanToEndEffectorPose`
    - [x] `PlanToEndEffectorOffset`
    - [ ] `PlanToTSR`
- [ ] `TSRPlanner`
    - [ ] `PlanToTSR`
- [ ] `NamedPlanner`
    - [ ] `PlanToNamedConfiguration`
- [x] `OMPLSimplifier`
    - [x] `ShortcutPath`
- [x] `OpenRAVERetimer`
    - [x] `RetimeTrajectory`
- [ ] `OpenRAVEAffineRetimer`
    - [ ] `RetimeTrajectory`
- [x] `ParabolicSmoother`
    - [x] `RetimeTrajectory`

**Comment by psigen** [comment]
This is a ton of work.  Maybe we should make intermediate PRs with partial coverage?  Are some of these already merged?

**Comment by mkoval** [comment]
I just merged a bunch of these tests in #169.
