### ISSUE TITLE
Iksolver reset to none

### ISSUE THREAD

**Issue by Stefanos19** [personalrobotics/prpy#114]
This is likely the same issue as https://github.com/personalrobotics/prpy/issues/111, but it appears also in the master version of prpy. After running [Jen's branch] (https://github.com/personalrobotics/ada_meal_scenario/tree/feature/action_framework) once, the iksolver is reset to none probably in some clone-bindings, and the planners that use an iksolver fail.

**Comment by mkoval** [comment]
Mostly a note to self...the problem is that CloneBindings only gets called
the first time an environment is used as a clone target. We need to
manually clear parent pointers in the target environment in prpy.Clone.

**Comment by Stefanos19** [comment]
Resolved with https://github.com/personalrobotics/prpy/commits/bugfix/CloneUserData
