### ISSUE TITLE
Add timing info to trajectory via tags

### ISSUE THREAD

**Issue by jeking04** [personalrobotics/prpy#133]
In the table_clearing demo we record time for planning, post-processing and execution.  Instead of doing this at the demo level, lets capture this data in prpy and add it as a tag to the output paths/trajectories.  Then table_clearing and future demos/benchmarks can just extract the data from trajectories and log it.

**Comment by psigen** [comment]
Uhh.. would it be possible to do this at the herbpy level instead?  Or make
it opt-in?  I already have to disable several loggers that spam planning
output I don't need.

**Comment by mkoval** [comment]
Closing because this was added in #136.

@psigen This adds trajectory **tags**, not log output. So there is no additional spam.

**Comment by psigen** [comment]
Ok, that's fine, thanks for the clarification.
