### ISSUE TITLE
TSR and TSRChain have no deserialize() function

### ISSUE THREAD

**Issue by mkoval** [personalrobotics/prpy#135]
These classes have `serialize`, but no `deserialize` function. Also, we may want to consider adding a second pair of `serialize` and `deserialize` functions that operate on dictionaries, instead of strings. This is useful for JSON, YAML, and Pickle serialization.

**Comment by psigen** [comment]
Note that the serialize function is the crazy one specifically for cbirrt.
I would not recommend using it for anything else. Instead, consider a
different set of methods like to_json/from_json.

**Comment by mkoval** [comment]
I added `serialize_dict` and `deserialize_dict` functions to `TSR` and `TSRChain` in #144. These functions operate on Python `dict` objects that can be serialized with `json` or `yaml`.

**Comment by psigen** [comment]
Could we rename these `to_dict()/from_dict()`?  The "serialize" terminology
isn't really used anywhere else in python, but "to"/"from" terminology is
used in numpy, pymongo, and other python libraries.  Thanks!

**Comment by cdellin** [comment]
+1 for to_dict/from_dict, serialize to me implies converting to a string or binary.  Converting to a dict representation is different.  The dict could then be serialized e.g. with pickle or json or what have you.

**Comment by psigen** [comment]
Created an updated interface here:
https://github.com/personalrobotics/prpy/pull/152

@cdellin: does this look good to you?

**Comment by cdellin** [comment]
API looks good!

**Comment by psigen** [comment]
@mkoval @cdellin: I think this issue is resolved with the latest few TSR refactors, right?

**Comment by cdellin** [comment]
@pseigen I think so!

**Comment by mkoval** [comment]
Yup! I'm closing this issue.
