### ISSUE TITLE
Hand Commands for Ada do nothing in Simulation

### ISSUE THREAD

**Issue by rachelholladay** [personalrobotics/prpy#155]
The commands:
-robot.arm.hand.OpenHand()
-robot.arm.hand.CloseHand()
-robot.arm.hand.CloseHandTight()

for ADA as listed in base/micohand.py do nothing in simulation. MoveHand(), however, does what you would expect.

**Comment by psigen** [comment]
Umm, am I missing something, or do these functions not actually get around to moving the hand anywhere in simulation?

https://github.com/personalrobotics/prpy/blob/f731c3c63b891c1393931ae33011d24a781bab43/src/prpy/base/micohand.py#L130

**Comment by mkoval** [comment]
@Stefanos19 Can you look into this?

**Comment by Stefanos19** [comment]
Fixed with PR #254
