### ISSUE TITLE
Remove default implementation of has_planning_method() from MetaPlanner

### ISSUE THREAD

**Issue by cdellin** [personalrobotics/prpy#158]
Mike wanted me to make an issue to remind him to do this. Below text is from him (on slack)

---

the default implementation of has_planning_method seems pretty bogus:

    def has_planning_method(self, method_name):
        for planner in self._planners:
            if planner.has_planning_method(method_name):
                return True

        return False

probably left over for backwards compatability. can you file an issue so I remember to remove it?

MetaPlanner inherits from Planner (which it should), but Planner has some default implementations that may not work on meta-planners

this all got messed up when we refactored the meta-planners...

**Comment by mkoval** [comment]
Fixed in #176.
