### ISSUE TITLE
What is the "feature/KinovaUpgrade" branch?

### ISSUE THREAD

**Issue by mkoval** [personalrobotics/prpy#181]
What is the [`feature/KinovaUpgrade`](https://github.com/personalrobotics/prpy/tree/feature/KinovaUpgrade) branch? Is this still necessary? If not, can I safely delete this?

@Stefanos19 @herlant @mharding01

**Comment by herlant** [comment]
Needs to be merged with master. Sorry I can't check now, but it does have something in it that changes with the new URDF. Maybe home configurations or something?

**Comment by mkoval** [comment]
@Stefanos19 Can you take a look at this and figure out if we should merge this as-is?

**Comment by mkoval** [comment]
Fixed in #186. Thanks @Stefanos19.
