### ISSUE TITLE
execute=True/False default value for PlanToNamedConfiguration()

### ISSUE THREAD

**Issue by DavidB-CMU** [personalrobotics/prpy#182]
1.
The prpy readme says that PlanToNamedConfiguration() should execute the trajectory by default, however apparently this feature was changed recently.

2.
The default value of this execute flag is different depending on the use case as shown below:

This is correct as per the recent change:

    # The arms do not move
    robot.PlanToNamedConfiguration('vertical')

    # The arms move
    robot.PlanToNamedConfiguration('vertical', execute=True)

The bug:

    # The arm moves immediately for this use case
    robot.right_arm.PlanToNamedConfiguration('vertical')

**Comment by mkoval** [comment]
I fixed this in #183. Can you test that branch and confirm that it works?
