### ISSUE TITLE
Typo in serialization?

### ISSUE THREAD

**Issue by Shushman** [personalrobotics/prpy#232]
https://github.com/personalrobotics/prpy/blob/372db4fe055e961c5969d97a3cf7de3e91fd241c/src/prpy/serialization.py#L294

I think this should be `reuse_bodies_dict` instead of `reuse_bodies`. Otherwise the immediately previous `if-else` block does not serve its purpose.

**Comment by mkoval** [comment]
I believe this is fixed by all of the ISER-related serialization changes. If not, please re-open this issue.
