### ISSUE TITLE
HauserParabolicSmoother ignores timelimit argument on construction

### ISSUE THREAD

**Issue by cdellin** [personalrobotics/prpy#248]
I tried to pass the `timelimit` parameter to the `prpy.planning.retimer.HauserParabolicSmoother` constructor, but when I attempt to smooth trajectories, the default limit of 3 sec is used instead.  It appears that the constructor parameter is inserted into a `self.default_options` dictionary which appears to be ignored when the instance's `RetimeTrajectory` planning method is called.  I'm happy to take a stab at this later, but I figured someone who knows this code better would know the short path to a fix.

**Comment by psigen** [comment]
@cdellin does #277 cover this?

**Comment by mkoval** [comment]
#277 should cover this. @cdellin please re-open this issue if it does not.
