### ISSUE TITLE
Rename SnapPlanner to StraightLinePlanner?

### ISSUE THREAD

**Issue by siddhss5** [personalrobotics/prpy#31]
I wonder if it might be more descriptive to rename it based on its new functionality. If you wanted to be super cool, you could rename it `GeodesicPlanner` :).

**Comment by psigen** [comment]
+1 for GeodesicPlanner!

**Comment by siddhss5** [comment]
I'm guessing 'GeodesicPlanner` is not happening @mkoval?

**Comment by mkoval** [comment]
I'm fine with either `GeodesicPlanner` or `SnapPlanner`. I wasn't sure if it was worth making a potentially breaking change just for the cosmetic improvement.

If you feel strongly about it, I can make this change and update AdaPy and HerbPy accordingly.

**Comment by mkoval** [comment]
I do like the name `GeodesicPlanner` but, unfortunately, there is no way to make this change without breaking backwards compatibility. We should keep it in mind next time we do make a breaking change.

**Comment by cdellin** [comment]
Why not rename it to `GeodesicPlanner`, subclassed by a wrapper called `SnapPlanner` which prints a warning when it's instantiated?

**Comment by psigen** [comment]
:+1: to @cdellin's suggestion.  `warnings.DeprecationWarning` ahoy!

**Comment by mkoval** [comment]
I'm fine with that if someone sends me a pull request. I don't feel strongly enough about the name to implement it myself. :)

@cdellin @psigen Any takers?
