### ISSUE TITLE
Modify CHOMPPlanner to throw more informative exceptions

### ISSUE THREAD

**Issue by mkoval** [personalrobotics/prpy#319]
It would be useful for CHOMP to throw `CollisionPlanningError` and `SelfCollisionPlanningError` to inform the user why planning failed. This information is available in C++ during the post-optimization verification step, but is not currently available in Python.

I suggest disabling the C++ verification and moving it to Python, where we can throw the appropriate exception classes.

**Comment by cdellin** [comment]
I support doing moving this to the PrPy wrapper ... note that you can pass `no_collision_check=True` to CHOMP, and it will skip the check in C++ land.

**Comment by mkoval** [comment]
This was resolved in #318.
