### ISSUE TITLE
Modifying robot DOF values in TSRPlanner causes weird downstream locking failures

### ISSUE THREAD

**Issue by cdellin** [personalrobotics/prpy#324]
This was provoked during development of #321 and #322.  We found a workaround for those, but this appears to be a deeper bug in PrPy, so I opened this issue.

The original bug was first reported in https://github.com/personalrobotics/prpy/pull/321#issuecomment-234697473 and https://github.com/personalrobotics/prpy/pull/322#issuecomment-234739584.  Here's what a failure looks like on the tableclearing demo:

```
$ rosrun table_clearing run.py --planner restart --nobowl --noglass --perception-sim
...
[INFO] [hgpc.actions.base:base.py:42]:__enter__: Validate precondition: None
[WARNING] [prpy.base.robot:robot.py:352]:PostProcessPath: Post-processing smooth paths is not supported. Using the default post-processing logic; this may significantly change the geometric path.
[INFO] [hgpc.actions.base:base.py:47]:__exit__: Validate postcondition: None
openravepy.interfaces.BaseManipulation: __del__, failed to lock environment for BaseManipulation.__del__!
[WARNING] [openravepy.interfaces.BaseManipulation:BaseManipulation.py:47]:__del__: failed to lock environment for BaseManipulation.__del__!
openravepy.interfaces.TaskManipulation: __del__, failed to lock environment for TaskManipulation.__del__!
[WARNING] [openravepy.interfaces.TaskManipulation:TaskManipulation.py:53]:__del__: failed to lock environment for TaskManipulation.__del__!
openravepy.inversekinematics: __del__, failed to lock environment for InverseKinematicsModel.__del__!
[WARNING] [openravepy.inversekinematics:inversekinematics.py:280]:__del__: failed to lock environment for InverseKinematicsModel.__del__!
openravepy.inversekinematics: __del__, failed to lock environment for InverseKinematicsModel.__del__!
[WARNING] [openravepy.inversekinematics:inversekinematics.py:280]:__del__: failed to lock environment for InverseKinematicsModel.__del__!
^\Quit
```
(I sent `SIGQUIT` after several minutes at the end because it seems to hang indefinitely.)

While debugging this, I was able to identify something interesting, which suggests a straightforward workaround for #321 and #322, but doesn't actually explain the bug.  Those changes move IK collision checking into the Python loop, instead of inside the `FindIKSolutions` call, so it can be done lazily.  Importantly, the current versions of both fixes don't wrap the robot posing code in a `RobotStateSaver`, so the initial configuration of the robot is different when the delegate planner is called.

I'm able to provoke the same weird locking errors in the above comment by adding the following code to the original (working) code which finds pre-checked IK solutions:
```
    for isol in range(ik_solution.shape[0]):
        robot.SetActiveDOFValues(ik_solution[isol,:])
```
Wrapping this in a `RobotStateSaver` no longer provokes the downstream issue.

I made a branch (https://github.com/personalrobotics/prpy/tree/bugfix/tsrplanner_locking_bug) which exhibits this on a simple `table_clearing` run:
```
$ rosrun table_clearing run.py --planner restart --nobowl --noglass --perception-sim
```
The added code is [here](https://github.com/personalrobotics/prpy/blob/73c57a87442e1c6373f7cf4c172d16d46e9a2db9/src/prpy/planning/tsr.py#L129).

I tried replacing the `delegate_planner` member with a planner which always fails immediately, and did not see the failure.  I also tried replacing with `SnapPlanner`, and I did see the failure.

**Comment by mkoval** [comment]
This is actually a locking issue in HGPC. Omitting the `RobotStateSaver` caused execution to fail because the robot is not close to the starting configuration of the trajectory. Raising that exception triggered the concurrency issue.

It is fixed in this pull request: https://github.com/personalrobotics/table_clearing/pull/37.
