### ISSUE TITLE
RetimeTrajectory uses lineartrajectoryretimer which ignores acceleration limits

### ISSUE THREAD

**Issue by siddhss5** [personalrobotics/prpy#34]
`RetimeTrajectory` runs the linear trajectory retimer when parabolic smoother fails. This is BAD because acceleration limits are ignored. We should rather throw an exception because we should really never have a timed trajectory that's not executable on the robot.
https://github.com/personalrobotics/prpy/blob/2898a89e35682d21d6354b137ad9903855fe7805/src/prpy/base/robot.py#L173

In the future we should use parabolic retimer. I'll put in a separate issue for this.

**Comment by mkoval** [comment]
This is fixed in my shortcutting/smoothing/retiming refactor branch: https://github.com/personalrobotics/prpy/tree/feature/SmoothingRefactor. I need to do a bit more testing before I can merge this in, but it should be done soon.
