### ISSUE TITLE
how to use prpy?

### ISSUE THREAD

**Issue by CxyCH** [personalrobotics/prpy#368]
how to use the package? I need to clone this package into my catkin_ws and use catkin_make then source it? I can't import prpy and there is no explain in the Readme.

**Comment by mkoval** [comment]
Yes, you are generally correct. You need to checkout `prpy` in a Catkin workspace, use `rosdep` to install its dependencies (primarily: OpenRAVE 0.9 or above), and run `catkin_make` (or `catkin build` if you are using `catkin_tools`).

There are detailed instructions for setting up your workspace [on this webpage](https://www.personalrobotics.ri.cmu.edu/software/development-environment). If you want an example to get started, I suggest working through [these instructions](https://github.com/personalrobotics/herbpy/blob/master/README.md) that describe how to get HERB up and running in simulation.

I hope that helps. We do need to update the `README` to include this information, too.
