### ISSUE TITLE
Issue with planners for ADA

### ISSUE THREAD

**Issue by Stefanos19** [personalrobotics/prpy#373]
When I pulled the latest master version from prpy, the robot.PlanToConfiguration in adapy returns the following error: 

```  File "/home/snikolai/ONR_DEMO_WS/src/ada/adapy/scripts/test.py", line 34, in <module>    robot.PlanToConfiguration(values, execute=True)  File "/home/snikolai/ONR_DEMO_WS/src/prpy/src/prpy/base/robot.py", line 118, in __getattr__ [INFO] [rospy.internal:core.py:138]:rospyinfo: topic[/rosout] adding connection to [/rosout], count 0    delegate_method = getattr(canonical.planner, name)  File "/home/snikolai/ONR_DEMO_WS/src/prpy/src/prpy/planning/base.py", line 253, in __getattr__    for planner in self.get_planners_recursive(method_name):  File "/home/snikolai/ONR_DEMO_WS/src/prpy/src/prpy/planning/base.py", line 232, in get_planners_recursive    sub_planners = planner.get_planners_recursive(method)  File "/home/snikolai/ONR_DEMO_WS/src/prpy/src/prpy/planning/base.py", line 230, in get_planners_recursive    for planner in self.get_planners(method):  File "/home/snikolai/ONR_DEMO_WS/src/prpy/src/prpy/planning/base.py", line 303, in get_planners    if planner.has_planning_method(method_name)] AttributeError: 'NoneType' object has no attribute 'has_planning_method' [INFO] [rospy.core:core.py:455]:signal_shutdown: signal_shutdown [atexit] [INFO] [rospy.internal:core.py:138]:rospyinfo: topic[/rosout] removing connection to /rosout ```

**Comment by brianhou** [comment]
That seems to suggest that one of the ADA planners is `None`? What's in `robot.planner`?

**Comment by Stefanos19** [comment]
Yup, we were missing or_trajopt from the ada_rosinstall. Thanks!
