### ISSUE TITLE
Increase granularity of exceptions thrown in PlanTo functions

### ISSUE THREAD

**Issue by ablasdel** [personalrobotics/prpy#45]
It would be a nice enhancement if, when the planners fail, if we can get more information about why it failed. 

For example:
Start configuration in collision
End configuration in collision
No plan found between Start/End

This would make it much easier to know how to react to failures in planning.

**Comment by mkoval** [comment]
To track our progress on this:

- @mkoval added collision exceptions to `VectorFieldPlanner` in #184
- @psigen added exceptions for precondition violations in #196 
- @lgw903 added specific start and goal collision exceptions to `SnapPlanner` and `GreedyIKPlanner` in #205

**Comment by mkoval** [comment]
This has been largely addressed by #184, #196, and #205.
