### ISSUE TITLE
Planning futures documentation

### ISSUE THREAD

**Issue by mkoval** [personalrobotics/prpy#48]
It would be great to have some documentation on what `defer=True` does internally. E.g.:

- What is the default behavior if I don't explicitly pass an `executor`?
- What do meta-planners that are inherently multithreaded (e.g. `Ranked`) do if `defer=False`?
- `concurrent.futures` vs `trollius.futures.future`?
- Are we using `deferred`s or `futures`?
- Can I use `inlineCallbacks`? Should I?

This is a follow-up from #47.

**Comment by psigen** [comment]
Where should we put this documentation?

**Comment by mkoval** [comment]
I suggest adding a section to the planning section of `README.md` for now. We really do need to split up that document, but that's something we should do as a separate PR.

**Comment by mkoval** [comment]
This is no longer relevant now that we've removed Trollius support in #278.
