### ISSUE TITLE
Error when simplifying a trajectory with DOFs that are not a subset of ActiveDOFs

### ISSUE THREAD

**Issue by jeking04** [personalrobotics/prpy#69]
Currently if a trajectory contains DOFs that are not currently active, the simplifier can produce a trajectory that is in collision.

**Comment by mkoval** [comment]
After implementing #95, I think we should retain this behavior. We explicitly set the DOFs in the trajectory as active in `PostProcessPath`. This is also similar to the behavior of the retiming code in `planningutils`.

If this becomes too inconvenient, we can add a helper function to `util` that sets the DOFs in the trajectory as active.

@jeking04 feel free to re-open this if you disagree. :smile:

**Comment by psigen** [comment]
Wait a second, @mkoval can you explain why producing an output that is *in collision* is a valid thing to do here?

I could understand only modifying certain DOFs when simplifying, returning an exception, or returning an unmodified path.

**Comment by mkoval** [comment]
The smoother only modifies the active DOFs. It only should collision check the links that are affected by the active DOFs. If other links are in collision in the input trajectory, then it's perfectly reasonable for the output to have the same collisions.

Or do you think that the simplifier is actively pushing those links in collision? I don't know which simplifier this is referring to (`OMPLSimplifier`, `ParabolicSmoother`, `HauserParabolicSmoother`?), so I can't replicate.
