### ISSUE TITLE
Various small errors in planners

### ISSUE THREAD

**Issue by jeking04** [personalrobotics/prpy#85]
During table_clearing testing I found four small problems:

1. If chomp planner ends up in collision, it throws an openravepy.openrave_exception which needs to be caught and re-raised as a PlanningError

2. In vectorfieldplanner the call to SetTrajectoryTags needs to be util.SetTrajectoryTags

3. The BiRRTPlanner does not have a PlanToConfiguration metho. This means the only planner that does have this method currently is chomp (or maybe traj_opt - i had to remove this from my workspace due to the PlanToTSR issue). We should add PlanToConfiguration to BiRRT.

4. chomp references prpy.tsr.TSR but doesn't import prpy.tsr

**Comment by mkoval** [comment]
We really do need to write some basic unit tests for these planners.As a start, it could be as simple as calling each planning method on a trivial environment and verifying that it returns success.

It's really frustrating that we find typos like this when running code on the real robot.
