### ISSUE TITLE
Ada should use NamedPlanner; not re-implement PlanToNamedConfiguration

### ISSUE THREAD

**Issue by mkoval** [personalrobotics/prpy#90]
The `Mico` class in PrPy currently [implements `PlanToNamedConfiguration`](https://github.com/personalrobotics/prpy/blob/master/src/prpy/base/mico.py#L131). We have the [`NamedPlanner` helper class](https://github.com/personalrobotics/prpy/blob/master/src/prpy/planning/named.py#L33) to avoid having to re-implement this on each robot. We should switch to this on ADA.

**Comment by Stefanos19** [comment]
Fixed by @mkoval , https://github.com/personalrobotics/prpy/pull/97
