### ISSUE TITLE
Ada has no IK solver loaded by default

### ISSUE THREAD

**Issue by mkoval** [personalrobotics/prpy#92]
There is no IK solver loaded by default on Ada. To replicate, run `robot.arm.GetIkSolver()` after calling `adapy.initialize()`. We should setup `or_nlopt_ik` with sane parameters by default in the `Mico` class. For planning to work in cloned environments, this needs to be done in both `__init__` and `CloneBindings`.

**Comment by Stefanos19** [comment]
Setting `or_nlopt_ik` to Ada and running cbirrt creates issue:
https://github.com/personalrobotics/prpy/issues/98

**Comment by Stefanos19** [comment]
Fixed by @mkoval https://github.com/personalrobotics/prpy/pull/97
