### ISSUE TITLE
Move robot-agnostic code from herbrobot.py and adarobot.py to robot.py

### ISSUE THREAD

**Issue by siddhss5** [personalrobotics/prpy#96]
@jeking04 and I spoke about this. There is a *lot* of robot-agnostic code in `herbrobot.py` that is duplicated in `adarobot.py` and likely `timrobot.py`. I suggest we move this all to `robot.py` and allow specific robots to override them if needed.
For example, [initializing the default planning pipeline] (https://github.com/personalrobotics/herbpy/blob/master/src/herbpy/herbrobot.py#L108), and [loading default TSRs from YAML] (https://github.com/personalrobotics/herbpy/blob/master/src/herbpy/herbrobot.py#L87).

**Comment by mkoval** [comment]
Fixed in #97.
